let scu =[
    { "name": "Hull E", "cargo_capacity_scu": 98304 },
    { "name": "Hull D", "cargo_capacity_scu": 20736 },
    { "name": "Javelin", "cargo_capacity_scu": 5400 },
    { "name": "Hull C", "cargo_capacity_scu": 4608 },
    { "name": "Kraken", "cargo_capacity_scu": 3792 },
    { "name": "Merchantman", "cargo_capacity_scu": 3584 },
    { "name": "Idris-P", "cargo_capacity_scu": 995 },
    { "name": "Idris-K", "cargo_capacity_scu": 995 },
    { "name": "Idris-M", "cargo_capacity_scu": 831 },
    { "name": "Kraken Privateer", "cargo_capacity_scu": 768 },
    { "name": "C2 Hercules", "cargo_capacity_scu": 624 },
    { "name": "Pioneer", "cargo_capacity_scu": 600 },
    { "name": "Caterpillar", "cargo_capacity_scu": 576 },
    { "name": "Endeavor", "cargo_capacity_scu": 500 },
    { "name": "890 Jump", "cargo_capacity_scu": 484 },
    { "name": "M2 Hercules", "cargo_capacity_scu": 468 },
    { "name": "Carrack", "cargo_capacity_scu": 456 },
    { "name": "Orion", "cargo_capacity_scu": 384 },
    { "name": "Hull B", "cargo_capacity_scu": 384 },
    { "name": "Genesis Starliner", "cargo_capacity_scu": 300 },
    { "name": "Starfarer", "cargo_capacity_scu": 291 },
    { "name": "Starfarer Gemini", "cargo_capacity_scu": 291 },
    { "name": "A2 Hercules", "cargo_capacity_scu": 234 },
    { "name": "Crucible", "cargo_capacity_scu": 230 },
    { "name": "Polaris", "cargo_capacity_scu": 216 },
    { "name": "Reclaimer", "cargo_capacity_scu": 180 },
    { "name": "Freelancer MAX", "cargo_capacity_scu": 120 },
    { "name": "Mercury Star Runner", "cargo_capacity_scu": 114 },
    { "name": "Constellation Andromeda", "cargo_capacity_scu": 96 },
    { "name": "MOLE", "cargo_capacity_scu": 96 },
    { "name": "Constellation Aquila", "cargo_capacity_scu": 96 },
    { "name": "Constellation Phoenix", "cargo_capacity_scu": 80 },
    { "name": "Corsair", "cargo_capacity_scu": 72 },
    { "name": "Freelancer", "cargo_capacity_scu": 66 },
    { "name": "Nautilus", "cargo_capacity_scu": 64 },
    { "name": "Hull A", "cargo_capacity_scu": 48 },
    { "name": "Cutlass Black", "cargo_capacity_scu": 46 },
    { "name": "600i Explorer", "cargo_capacity_scu": 40 },
    { "name": "Hammerhead", "cargo_capacity_scu": 40 },
    { "name": "Freelancer MIS", "cargo_capacity_scu": 36 },
    { "name": "Prospector", "cargo_capacity_scu": 32 },
    { "name": "Valkyrie", "cargo_capacity_scu": 30 },
    { "name": "Freelancer DUR", "cargo_capacity_scu": 28 },
    { "name": "Apollo Triage", "cargo_capacity_scu": 28 },
    { "name": "Apollo Medivac", "cargo_capacity_scu": 28 },
    { "name": "Nomad", "cargo_capacity_scu": 24 },
    { "name": "600i Touring", "cargo_capacity_scu": 16 },
    { "name": "Vulcan", "cargo_capacity_scu": 12 },
    { "name": "Cutlass Blue", "cargo_capacity_scu": 12 },
    { "name": "Vulture", "cargo_capacity_scu": 12 }
  ]
  